### PR TITLE
kde fix

### PR DESCRIPTION
**Pull request by sevku**
I think I fixed it for KDE. It works for me, however, only when using Python 2.7. It doesn't work with current Python version.

Also, it opens it with Midori, even though Firefox is set as standard. Not sure if that's supposed to be the case.

### CODE REVIEW

**Comment by sevku** [comment]
I didn't test if setting the standard actually works

**Comment by davesteele** [comment]
Looks OK. I want to review it in more detail before merging, though. 

You are probably going to need Python 3 support before long.

[This](https://github.com/davesteele/gnome-gmail/blob/1d99a4464edc410e9ebfc87ef38806b8731575be/gnomegmail.py#L145) is supposed to get the correct "standard" browser. Perhaps KDE needs a special case here.

**Comment by sevku** [comment]
> Looks OK. I want to review it in more detail before merging, though.
> 
> You are probably going to need Python 3 support before long.
> 
> [This](https://github.com/davesteele/gnome-gmail/blob/1d99a4464edc410e9ebfc87ef38806b8731575be/gnomegmail.py#L145) is supposed to get the correct "standard" browser. Perhaps KDE needs a special case here.

That works in KDE too.

**Comment by sevku** [comment]
might want to link #78

**Pull request merged**
