### PR TITLE
Handle missing ~/.kde/share/config/emaildefaults gracefully

### PR DESCRIPTION
**Pull request by scop**
Note: I have not actually tested this change, but I believe it should work. More info: https://bugzilla.redhat.com/show_bug.cgi?id=1316212

### CODE REVIEW

**Comment by davesteele** [comment]
Looks reasonable. The real problem is that I stepped away from the KDE code after failing to getting it to work properly - reporting and setting the standard mailer.

**Comment by scop** [comment]
@davesteele any help needed with this? Looks like people are still running into this, https://bugzilla.redhat.com/show_bug.cgi?id=1409253

**Comment by davesteele** [comment]
In a word - yes. I've not merged this change because KDE support is broken in general. The failure here just makes that fact more explicit.

**Comment by sevku** [comment]
I believe the path `~/.kde/share/config/emaildefaults` should in fact be `/usr/share/applications/defaults.list`

**Comment by davesteele** [comment]
@sevku, if you get it working, please send me a pull request.

**Pull request merged**
